### ISSUE TITLE
Moving tasks from list to list suddenly stopped working 

### ISSUE THREAD

**Issue by jmtalarn** [jmtalarn/strikethru#9]
Moving tasks from list to list suddenly stopped working

**Comment by rgraciama** [comment]
On editing task view. If u move a task from list to another list, it dissapears.

1) From Vault to Live. ( _ )
2) From Vault to Dump. ( _ )
3) From Dump to Live. ( _ )
4) From Dump to Vault. ( _ )
5) From Live to Dump. ( _ )
6) From Live to Vault. ( _ )
